version: "3.8"

services:
  dyvpromo:
    container_name: dyvpromo
    build: ./
    ports:
      - "8899:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
